# Generated by Django 5.2.17 on 2026-08-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อสินค้า')),
                ('description', models.TextField(verbose_name='รายละเอียด')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา')),
                ('stock', models.IntegerField(verbose_name='จำนวนในสต็อก')),
                ('category', models.CharField(choices=[('IT', 'อุปกรณ์ไอที'), ('OFFICE', 'เครื่องใช้สำนักงาน'), ('BOOK', 'หนังสือ')], max_length=20, verbose_name='หมวดหมู่')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='วันที่เพิ่มข้อมูล')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='รูปภาพสินค้า')),
            ],
        ),
    ]
