# Generated by Django 5.2.17 on 2026-08-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อ-นามสกุล')),
                ('position', models.CharField(max_length=50, verbose_name='ตำแหน่ง')),
                ('salary', models.IntegerField(verbose_name='เงินเดือน')),
                ('email', models.EmailField(max_length=254, verbose_name='อีเมล')),
                ('hire_date', models.DateField(verbose_name='วันที่เริ่มงาน')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='รูปพนักงาน')),
            ],
        ),
    ]
